server:
  session-timeout: 1800
  tomcat:
        max-threads: 1000
        min-spare-threads: 30
  port: 8092
  uri-encoding: utf-8
  context-path: /async

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #指定bean所在包
  typeAliasesPackage: com.dms.data.consume.**.entity
  #指定映射文件
  mapper-locations: classpath:mapper/**/*.xml

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: countSql



