
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.22.102:3306/DFMALL_S?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&useAffectedRows=true
    username: hzmall
    password: hYZ!ns^ZziS3
    druidusername: qazwsx
    druiduserpassword: qazwsx
    initialSize: 10
    minIdle: 10
    maxActive: 50
    maxWait: 60000                           # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 30000        # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true            # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j                # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录

  rabbitmq:
    address: 192.168.1.48:5672,192.168.1.49:5672
    username: admin
    password: admin
    virtual-host: /
